% Convert roll, pitch, yaw angles to rotation matrix
% N.B. alpha is around Z, beta around Y and gamma around X

function R=rpy2rot(alpha,beta,gamma)

R=[cos(alpha)*cos(beta),(-sin(alpha)*cos(gamma)+cos(alpha)*sin(beta)*sin(gamma)),...
    (sin(alpha)*sin(gamma)+cos(alpha)*sin(beta)*cos(gamma));...
    sin(alpha)*cos(beta),(cos(alpha)*cos(gamma)+sin(alpha)*sin(beta)*sin(gamma)),...
    (-cos(alpha)*sin(gamma)+sin(alpha)*sin(beta)*cos(gamma));...
    -sin(beta),cos(beta)*sin(gamma),cos(beta)*cos(gamma)];